import { useSession } from "next-auth/react";
import "../globals.css";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isAuthorized = true;

  if (!isAuthorized) {
    redirect("/");
    return null;
  }
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
